name: Check contents

on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}

jobs:
    check-content:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                repository: viper-adnan/dood-crawler
                token: ${{ secrets.TOKEN }}

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  cache: pip

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt

            - name: Download artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  name: entries-data
                  workflow_conclusion: ""
                  check_artifacts: true
                  if_no_artifact_found: warn

            - name: Run check script
              timeout-minutes: 60
              env:
                  CONFIG: ${{ secrets.CONFIG }}
              run: |
                  python3 -m src

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: entries-data
                  path: entries-data.json
